project:
  type: website
  output-dir: docs

website:
  title: "PSYC 2020L"
  description: "Webpage for Psychological Statistics Lab taught at Georgia Tech in Fall 2025."
  site-url: "https://jhelmer3.github.io/PSYC2020L/"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    grid:
      body-width: 800px
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true




