---
title: "Psychological Statistics Lab"
subtitle: "Fall 2025"
date: last-modified
author: "Jessica Helmer"
---

## Overview

Welcome to the website for PSYC 2020-A01 **Psychological Statistics** / **PSYC 6022-A01 Psychological Statistics for HCI** for Fall 2025! Usage of this site is *not* required—I will always keep the [Canvas](https://www.canvas.gatech.edu/) page updated. However, if this page is helpful to you, feel free to use it!

## posit::conf(2025)

Attend livestreamed sessions at posit::conf(2025) as an extra credit opportunity! See here for [instructions](/labs/Extra Credit/Extra Credit 1.qmd).

## Labs

:::: {.columns}
::: {.column width=33%}
### 08/22 - Lab 1
#### Basic R
[Slides](/labs/Lab 1 - Basic R/PSYC2020L Lab 1.qmd) | [Assignment](/labs/Lab 1 - Basic R/PSYC2020L Assignment 1.Rmd)
:::

::: {.column width=33%}
### 08/29 - Lab 2
#### Central Tendency
[Slides](/labs/Lab 2 - Central Tendency/PSYC2020L Lab 2.qmd) | [Assignment](/labs/Lab 2 - Central Tendency/PSYC2020L Assignment 2.Rmd)
:::

::: {.column width=33%}
### 09/05 - Lab 3
#### Measures of Variability
[Slides](/labs/Lab 3 - Measures of Variability/PSYC2020 Lab 3.qmd) | No Assignment
:::
::::

:::: {.columns}
::: {.column width=33%}
### 09/12 Lab 4
#### Z-Scores
[Slides](/labs/Lab 4 - Z-Scores/PSYC2020 Lab 4.qmd) | [Assignment](/labs/Lab 4 - Z-Scores/PSYC2020L Assignment 4.Rmd)
:::

::: {.column width=33%}
### 09/19 Lab 5
#### Intermediate R
[Slides](/labs/Lab 5 - Intermediate R/PSYC2020 Lab 5.qmd) | [Assignment](/labs/Lab 5 - Intermediate R/PSYC2020L Assignment 5.Rmd)
:::

::: {.column width=33%}
### 09/26 Lab 6
#### Sampling Distributions
[Slides](/labs/Lab 6 - Sampling Distributions/PSYC2020 Lab 6.qmd) | [Assignment](/labs/Lab 6 - Sampling Distributions/PSYC2020L Assignment 6.Rmd)
:::
::::

:::: {.columns}
::: {.column width=33%}
### 10/03 Lab 7
#### NHST I
[Slides](/labs/Lab 7 - NHST I/PSYC2020 Lab 7.qmd) | [Assignment](/labs/Lab 7 - NHST I/PSYC2020L Assignment 7.Rmd)
:::

::: {.column width=33%}
### 10/10 Lab 8
#### NHST II
[Slides](/labs/Lab 8 - NHST II/PSYC2020 Lab 8.qmd) | [Assignment](/labs/Lab 8 - NHST II/Lab 8 Assignment.Rmd) 
:::

::: {.column width=33%}
### 10/17 Lab 9
#### Confidence Intervals
[Slides](/labs/Lab 9 - Confidence Intervals/PSYC2020 Lab 9.qmd) | [Assignment](/labs/Lab 9 - Confidence Intervals/Lab 9 Assignment.Rmd) 
:::
::::


:::: {.columns}
::: {.column width=33%}
### 10/24 Lab 10
#### Advanced R
[Slides](/labs/Lab 10 - Advanced R/PSYC2020 Lab 10.qmd) | [Assignment](/labs/Lab 10 - Advanced R/Lab 10 Assignment.Rmd) 
:::

::: {.column width=33%}
### 10/31 Lab 11 🎃
#### Independent and Paired Samples *T*-Test
[Slides](/labs/Lab 11 - Independent and Paired Sample T-Test/PSYC2020 Lab 11.qmd) | No Assignment
:::

::: {.column width=33%}
### 11/07 Lab 12
#### Chi-Squared Test
[Slides](/labs/Lab 12 - Chi-Squared Test/PSYC2020 Lab 12.qmd) | [Assignment](/labs/Lab 12 - Chi-Squared Test/Lab 12 Assignment.Rmd)
:::
::::

:::: {.columns}
::: {.column width=33%}
### 11/14 Lab 13
#### Correlation and Regression
Coming soon!
:::

::: {.column width=33%}
### 11/21 Lab 14
#### One-Way ANOVA
Coming soon!
:::

::: {.column width=33%}
### End of Semester!!
:::
::::
